# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [16]:
import numpy as np

array = np.random.randint(1,21,size= (5,5))
print(f"Original Array: \n",array)

array[:,2] =  1
print("Modified Array:\n")
print(array)


Original Array: 
 [[ 1  8  4 10 18]
 [18 14  1 18  1]
 [ 5  8 14  1 11]
 [15  8 10 15  5]
 [17  8 11 18 17]]
Modified Array:

[[ 1  8  1 10 18]
 [18 14  1 18  1]
 [ 5  8  1  1 11]
 [15  8  1 15  5]
 [17  8  1 18 17]]


In [24]:
array1 = np.arange(1,17).reshape((4,4))
print(array1)

np.fill_diagonal(array1,0)
print("Modified array: \n")
print("Modified array:")
print(array1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array: 

Modified array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [28]:
array = np.arange(1,37).reshape(6,6)
print("Original Array:")
print(array)

sub_array = array[2:5,1:4]
print("Sub-array : \n")
print(sub_array)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array : 

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [33]:
# Create a NumPy array of shape (5, 5) with random integers
arr = np.random.randint(1,21,size=(5,5))
print("Original Array: \n")
print(arr)

#Extract the elemet at border
border_element = np.concatenate((arr[0, :],arr[-1,:],arr[1:-1,0],arr[1:-1,-1]))
print("border_element : \n")
print(border_element)

Original Array: 

[[ 5  3 11  5 13]
 [ 1  1  7 19 20]
 [13  9 11  8 19]
 [18  8  4 10 15]
 [14  1 20  3 11]]
border_element : 

[ 5  3 11  5 13 14  1 20  3 11  1 13 18 20 19 15]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [40]:
arr1 = np.random.randint(1,11,size=(3,4))
arr2 = np.random.randint(1,11,size=(3,4))

print("Array 1:")
print(arr1)
print("Array2:")
print(arr2)

#perform element wise operation
addition = arr1 +arr2
subtraction = arr1 -arr2
multiplication = arr1 * arr2
division = arr1/arr2
print("\n")
print("Element wise Addition :")
print(addition)
print("Element wise Subtraction : ")
print(subtraction)
print("Element wise Multiplication :")
print(multiplication)
print("Element wise Division : ")
print(division)


Array 1:
[[6 2 4 9]
 [7 9 9 7]
 [9 5 6 7]]
Array2:
[[ 2  3 10  3]
 [ 5  7  8  4]
 [ 3  1  1  8]]


Element wise Addition :
[[ 8  5 14 12]
 [12 16 17 11]
 [12  6  7 15]]
Element wise Subtraction : 
[[ 4 -1 -6  6]
 [ 2  2  1  3]
 [ 6  4  5 -1]]
Element wise Multiplication :
[[12  6 40 27]
 [35 63 72 28]
 [27  5  6 56]]
Element wise Division : 
[[3.         0.66666667 0.4        3.        ]
 [1.4        1.28571429 1.125      1.75      ]
 [3.         5.         6.         0.875     ]]


In [48]:
array = np.arange(1,17).reshape(4,4)
print("original array:")
print(array)

row_sum = np.sum(array,axis=1)
column_sum = np.sum(array,axis=0)
print("Row-Wise Sum :")
print(row_sum)
print("Column-wise Sum :")
print(column_sum)



original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-Wise Sum :
[10 26 42 58]
Column-wise Sum :
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [52]:
array = np.random.randint(1,21,size=(5,5))
print("Original Array :")
print(array)

mean = np.mean(array)
median = np.median(array)
std_div = np.std(array)
variance = np.var(array)

print(f"Mean :{mean}")
print(f"Median :{median}")
print(f"Standard Deviation:", std_div)
print(f"Variance:",variance)

Original Array :
[[18 16 10 11 18]
 [ 5 19 15  7 11]
 [17  8 16 18 11]
 [ 4  6  9  5 14]
 [16 11  5 11  8]]
Mean :11.56
Median :11.0
Standard Deviation: 4.733539901595845
Variance: 22.406399999999998


In [57]:
array = np.arange(1,10).reshape(3,3)
print("original array")
print(array)

mean = np.mean(array)
std_div = np.std(array)

Normalized_array = (array - mean)/std_div
print(f"Normalized_array :\n{Normalized_array}")

original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized_array :
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [59]:
array = np.random.randint(1,11,size=(3,3))
row_array = np.random.randint(1,11,size=(3,))
print(" Original Array:")
print(array)
print("1D array :")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = array + row_array
print("Rsulting Array :")
print(result)

 Original Array:
[[ 5  6  1]
 [10  7 10]
 [ 5  7  4]]
1D array :
[8 7 7]
Rsulting Array :
[[13 13  8]
 [18 14 17]
 [13 14 11]]


In [63]:
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array
print("Resulting array:")
print(result)
new = array - column_array[:, np.newaxis]
print("new")
print(new)

Original array:
[[10  7  3  9]
 [ 5  3  2  5]
 [ 5  1  3  4]
 [10 10  8  5]]
1D array:
[3 7 5 9]
Resulting array:
[[ 7  0 -2  0]
 [ 2 -4 -3 -4]
 [ 2 -6 -2 -5]
 [ 7  3  3 -4]]
new
[[ 7  4  0  6]
 [-2 -4 -5 -2]
 [ 0 -4 -2 -1]
 [ 1  1 -1 -4]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [74]:
arr = np.random.randint(1,11,size=(3,3))
print("original array:")
print(arr)

determinat = np.linalg.det(arr)
print(f"Determinat : \n {determinat}")

inverse = np.linalg.inv(arr)
print(f"Inverse : \n {inverse}")

eign = np.linalg.eigvals(arr)
print(f"Eigen value : \n {eign}")




original array:
[[5 3 7]
 [3 3 6]
 [2 8 9]]
Determinat : 
 -23.999999999999982
Inverse : 
 [[ 0.875      -1.20833333  0.125     ]
 [ 0.625      -1.29166667  0.375     ]
 [-0.75        1.41666667 -0.25      ]]
Eigen value : 
 [15.8986783 +0.j  1.89705857+0.j -0.79573687+0.j]


In [84]:
arr1 = np.random.randint(1,11,size=(2,3))
arr2 = np.random.randint(1,11,size=(3,2))
print("Array 1 :")
print(arr1)
print("Array2 :")
print(arr2)

#perform matrix multiplication
result = np.dot(arr1,arr2)
result1 = arr1 @ arr2
print("Matrix Multiplication Result :")
print(result)
print("Second way:")
print(result1)


Array 1 :
[[2 9 8]
 [7 9 2]]
Array2 :
[[ 4 10]
 [ 4  9]
 [ 6 10]]
Matrix Multiplication Result :
[[ 92 181]
 [ 76 171]]
Second way:
[[ 92 181]
 [ 76 171]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [87]:
array = np.arange(1,10).reshape(3,3)
print("Original Array:")
print(array)

reshaped_array = array.reshape(1,9)
print(reshaped_array)

reshaped_array_2 = array.reshape(9,1)
print(reshaped_array_2)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [93]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

flattened_array = array.flatten()
print("Flatterned Array :")
print(flattened_array)

reshaped_arr = flattened_array.reshape(5,5)
print("reshaped_arr :")
print(reshaped_arr)

Original array:
[[10  3 13  3  8]
 [ 3 20  9 19 15]
 [ 2  3 13 11  4]
 [19  5 11  3 18]
 [ 4 20 12  9  1]]
Flatterned Array :
[10  3 13  3  8  3 20  9 19 15  2  3 13 11  4 19  5 11  3 18  4 20 12  9
  1]
reshaped_arr :
[[10  3 13  3  8]
 [ 3 20  9 19 15]
 [ 2  3 13 11  4]
 [19  5 11  3 18]
 [ 4 20 12  9  1]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [101]:
array = np.random.randint(1,21,size=(5,5))
print("Original array:")
print(array) 

# Fancy indexing
corner = array[[0,0,-1,-1],[0,-1,0,-1]]
print("corner elements:")
print(corner)

Original array:
[[15 20  4  3 16]
 [ 8  8 10 15  2]
 [17  9 13 19  9]
 [15  8  5 19 10]
 [20 12 10  8  2]]
corner elements:
[15 16 20  2]


In [102]:
array = np.random.randint(1,21,size=(4,4))
print("Original array :")
print(array)

array[array>10]=10
print("Modified array")
print(array)

Original array :
[[ 6 14  8 16]
 [14  9  4  6]
 [16  4 14 14]
 [ 3 13 17  7]]
Modified array
[[ 6 10  8 10]
 [10  9  4  6]
 [10  4 10 10]
 [ 3 10 10  7]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [104]:
data_type = [('Name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alice',23,55.6),('bob',32,66.43),('Jack',13,34.2)],dtype=data_type)
print("Original Array :")
print(data)

sorted_array = np.sort(data,order='age')
print("Sorted array by age:")
print(sorted_array)

Original Array :
[('Alice', 23, 55.6 ) ('bob', 32, 66.43) ('Jack', 13, 34.2 )]
Sorted array by age:
[('Jack', 13, 34.2 ) ('Alice', 23, 55.6 ) ('bob', 32, 66.43)]


In [107]:
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)],dtype=data_type)
print("Original array")
print(data)

distance = np.sqrt((data['x'][:,np.newaxis]-data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)
print("Euclidean distance:")
print(distance)

Original array
[(1, 2) (3, 4) (5, 6)]
Euclidean distance:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [109]:
import numpy.ma as ma 

array = np.random.randint(1,21,size=(4,4))
masked_array = ma.masked_greater(array,10)
print("original array")
print(array)
print("Masked array :")
print(masked_array)

sum_unmasked = masked_array.sum()
print("Sum of Unmasked elements:",sum_unmasked)

original array
[[ 2  2  7 18]
 [ 8  4 14  8]
 [ 4  5 18 11]
 [12  3 11  4]]
Masked array :
[[2 2 7 --]
 [8 4 -- 8]
 [4 5 -- --]
 [-- 3 -- 4]]
Sum of Unmasked elements: 47


In [118]:
array = np.random.randint(1,21,size=(3,3))
masked_array = ma.masked_array(array,mask = np.eye(3,dtype=bool))
print("Original array : ")
print(array)
print("masked_array")
print(masked_array)

mean_unmasked = masked_array.mean()
print(f"mean : {mean_unmasked}")
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array :")
print(masked_array)

Original array : 
[[15  2 15]
 [ 3 17  1]
 [ 8  9  8]]
masked_array
[[-- 2 15]
 [3 -- 1]
 [8 9 --]]
mean : 6.333333333333333
Modified masked array :
[[ 6  2 15]
 [ 3  6  1]
 [ 8  9  6]]
