##### Numpy is the fundamental library for scientific computing in python. it provide support for array and matrices,along with the collection of mathematical functions to operate on this data structure. in this lesson we will cover the basics of NumPy,focusing on array and vectorized operations.

In [3]:
!pip install numpy

In [4]:
import numpy as np
np.array([1,2])

array([1, 2])

In [5]:
import numpy as np

# Create a array using numpy
# Create a 1D-array

arr1 = np.array([2,3,1,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[2 3 1 5]
<class 'numpy.ndarray'>
(4,)


In [ ]:
arr2 = np.array([2,3,4,5,1])
arr2.reshape(1,5) # 1 rows and 5 columns


array([[2, 3, 4, 5, 1]])

In [10]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2.shape)

(1, 5)


In [12]:
arr2 = np.array([[1,2,3,4,5],[3,2,1,5,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [3 2 1 5 7]]
(2, 5)


In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#Identitiy Mtrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# attributes of Numpy array

arr = np.array([[1,2,3],[4,5,6]])
print("array: \n", arr)
print("Shape:", arr.shape)
print("Number Of Dimensions :",arr.size)
print("Size(number of Elements) :",arr.size)
print("Data type :",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number Of Dimensions : 6
Size(number of Elements) : 6
Data type : int64
Item size (in bytes): 8


In [ ]:
### Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element-wise addition
print("Addition:", arr1 + arr2)

# Element-wise subtraction
print("Subtraction:", arr2 - arr1)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)


Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [38]:
# Universal Functions

arr = np.array([2,3,4,5,6])
#Square root
print(np.sqrt(arr))
#Exponential 
print(np.exp(arr))
#Sin 
print(np.sin(arr))
#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [48]:
# array slicing and indexing

arr = np.array([[1,2,3,6],[4,5,6,2],[7,8,9,1]])
print(" Array : \n",arr)

 Array : 
 [[1 2 3 6]
 [4 5 6 2]
 [7 8 9 1]]


In [45]:
print(arr[0][0])

1


In [52]:
arr[1:,2:]

array([[6, 2],
       [9, 1]])

In [54]:
print(arr[1,1:3])

[5 6]


In [55]:
# Modify array Elements
arr[0][0]=100
print(arr)

[[100   2   3   6]
 [  4   5   6   2]
 [  7   8   9   1]]


In [60]:
arr[1:][1:]= 100
print(arr)

[[100   2   3   6]
 [100 100 100 100]
 [100 100 100 100]]


In [61]:
### Statistical Concept - Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalize_data = (data - mean)/std_dev
print("Normalized data:",normalize_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [62]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean 
mean = np.mean(data)
print("Mean :",mean)

#Median
median = np.median(data)
print("Median :",median)

#standard Deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

#Variance
variance = np.var(data)
print("Variance :",variance)

Mean : 5.5
Median : 5.5
Standard Deviation: 2.8722813232690143
Variance : 8.25


In [66]:
# Logical Operation 

data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
data[data>5]


[False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [67]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])